### ISSUE TITLE
TypeScript reports errors after upgrading from 0.5.5 to 1.1.0

### ISSUE THREAD

**Issue by doberkofler** [webpack-contrib/html-loader#277]
- Operating System: macOS 10.15.4
- Node Version: 12.16.1
- NPM Version: 6.14.4
- webpack Version: 4.42.1
- html-loader Version: 1.1.0

### Actual Behavior

After upgrading from version 0.5.5 to version 1.1.0 when using the TypeScript tsc command to compile/lint my TypeScript code base, I get the following errors:

```
> tsc --noEmit --project ./tsconfig.json

node_modules/@types/domutils/index.d.ts:6:10 - error TS2614: Module '"../../../../../../../../../Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/domhandler/lib"' has no exported member 'DomElement'. Did you mean to use 'import DomElement from "../../../../../../../../../Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/domhandler/lib"' instead?

6 import { DomElement } from "domhandler";
           ~~~~~~~~~~

node_modules/@types/htmlparser2/index.d.ts:17:10 - error TS2614: Module '"../../../../../../../../../Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/domhandler/lib"' has no exported member 'DomElement'. Did you mean to use 'import DomElement from "../../../../../../../../../Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/domhandler/lib"' instead?

17 export { DomElement, DomHandlerOptions, DomHandler, Element, Node } from 'domhandler';
            ~~~~~~~~~~

node_modules/@types/react-html-parser/index.d.ts:9:10 - error TS2305: Module '"../../../../../../../../../Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/htmlparser2/lib"' has no exported member 'DomElement'.

9 import { DomElement } from "htmlparser2";
           ~~~~~~~~~~
```

Simply reverting back to html-loader version 0.5.5 fixes the problem.

**Comment by evilebottnawi** [comment]
Why do you check types in node_modules :confused:? Disable it

**Comment by doberkofler** [comment]
1) The problem can be directly linked to the upgrade from 0.5.5 to 1.1.0 without any other configuration change. This is why I assumed that it is linked to this loader or one of it's dependencies.

2) Checking the `node_modules` folder is disabled:

```json
{
  "compilerOptions": {
    "extendedDiagnostics": false,
    "noEmit": true,
    "downlevelIteration": true,
    "allowJs": true,
    "checkJs": false,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": false,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "esModuleInterop": true,
    "declaration": false,
    "importHelpers": true,
    "moduleResolution": "node",
    "target": "es2015",
    "module": "esnext",
    "jsx": "react",
    "baseUrl": "../",
    "outDir": "../temp",
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by evilebottnawi** [comment]
You need double check ts configuration, we don't have types, we don't provide types and nothing do with types, we even used typescript here, and you can see what errors from `node_modules`

**Comment by doberkofler** [comment]
I've already did before opening the SR but without any change except the upgrade of `html-loader` and the fast that reverting to the original version fixes the problem, I really cannot imagine any other reason. Do you? I will check once more!
The error message actually suggests that the dependency `htmlparser2` might actually be the source of the problem but I did not find anything there.

**Comment by evilebottnawi** [comment]
@doberkofler please create reproducible test repo. I repeat that we do not contain types, and cannot make fix in projects that are our dependencies, how do you imagine we can fix that?

**Comment by doberkofler** [comment]
@evilebottnawi I was able to extract a minimalistic test case.
After `npm i` just run `npm run type-check` and you should see the error.

[html-loader.zip](https://github.com/webpack-contrib/html-loader/files/4427231/html-loader.zip)

**Comment by evilebottnawi** [comment]
Please use `"skipLibCheck":  true`

**Comment by doberkofler** [comment]
@evilebottnawi Thank you for your help.
This works but it actually feels more like a workaround for a type error that an actual solution for the problem. 
It seems to me, as if there is some type mixup between the `@types/react-html-parser` module and a dependency of the `html-loader` module.
Would you agree?

**Comment by evilebottnawi** [comment]
Maybe, I don't look at that, you can open an issue in `react-html-parser` repo, `skipLibCheck` is used many projects, it is not workaround, you don't need linting types for dependencies, it can contains old/broken types/used old version of typescript/other strange problems
